### ISSUE TITLE
Getting Error while creating Conda Environment with requirements.txt

### ISSUE THREAD

**Issue by Karn3003** [HaoZhongkai/GNOT#1]
PackagesNotFoundError: The following packages are not available from current channels:

  - einops==0.6.0
  - dgl==1.0.1+cu116
  - torch==1.10.0
  - scikit_learn==1.2.1

**Comment by HaoZhongkai** [comment]
hi, I'm not sure which package is not found. If it is dgl or torch, I recommend you to install them using commands from the official website, https://www.dgl.ai/pages/start.html and https://pytorch.org/get-started/previous-versions/  . As for scikit-learn, it seems 1.2.1 is not available , you could install another version (like newest version) instead. I will modify this error later

**Comment by Karn3003** [comment]
Hi, I think there was an issue with dgl package as I got the following error while installing with pip install -r requiements.txt

ERROR: Could not find a version that satisfies the requirement dgl==1.0.1+cu116 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.4.3, 0.4.3.post1, 0.4.3.post2, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.0.post1, 0.6.1, 0.9.0, 0.9.1, 1.0.0, 1.0.1, 1.0.4, 1.1.0, 1.1.1)
ERROR: No matching distribution found for dgl==1.0.1+cu116.

The following command worked for me.
pip install  dgl -f https://data.dgl.ai/wheels/cu116/repo.html
pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html

**Comment by HaoZhongkai** [comment]
OK! I got it and I will push changes to resolve this problem.

**Comment by Karn3003** [comment]
Also do change the torch version as getting the following error while running the train.py

RuntimeError: DGL requires PyTorch >= 1.12.0

Also getting the following error.
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/ece/hdd/anaconda3/envs/GFNO/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'

**Comment by Karn3003** [comment]
Hi, I will suggest changing requirements.txt file to not have the version for all libraries and directly install the latest version of all libraries as it worked out for me.
Later run the command:
pip install -r requirements.txt --upgrade

**Comment by HaoZhongkai** [comment]
Thanks, I'm going to push requirements without specific version for dgl and pytorch

**Comment by Karn3003** [comment]
Hi, @HaoZhongkai Can you please explain the usage of the following argument? As I read the paper and maybe missed out something due to which I haven't got it.
This argument:
Theta: (N_theta,) numpy array, global parameters for this sample

N_theta: dimension of global parameters

what does global means here??

**Comment by Karn3003** [comment]
@HaoZhongkai It would be great if you can help me above query as I need to run the model for different dataset.

**Comment by HaoZhongkai** [comment]
Hi,  as shown in the paper, input fields for some problems are not a function defined on a mesh, they might be just a vector parameter. For example, take NS2d-c dataset, we have multiple (u,v,p) fields with different locations of obstacles. The positions (xi,yi,ri) for these obstacles could be viewed as global parameters.
