### ISSUE TITLE
Viscocity of NS 2D from Li et al

### ISSUE THREAD

**Issue by Karn3003** [HaoZhongkai/GNOT#13]
Hi, I wanted to know about the setting for the NS 2D as haven't found it in the paper.

**Comment by Karn3003** [comment]
Also, in the Drive, I couldn't find the heatsink3d dataset.

**Comment by HaoZhongkai** [comment]
Hi, 
 The settings of NS2d-C are shown in Page 11. The NS2d dataset is from FNO paper (https://arxiv.org/abs/2010.08895).
  The heatsink dataset is at https://onedrive.live.com/?authkey=%21ANwGKa5MYmVtKlg&id=BA5019AD82B64393%21315402&cid=BA5019AD82B64393

**Comment by Karn3003** [comment]
Hi, 
in NS2dC, I wanted to know which viscosity coeff and what train and test split.

Thanks

**Comment by HaoZhongkai** [comment]
Hi,




  rho=mu=1 is used in the NS2d-C. Attached is the comsol file.




best regards,

Zhongkai Hao 







-----原始邮件-----
发件人:"Karn Tiwari" ***@***.***>
发送时间:2024-06-20 11:56:02 (星期四)
收件人: HaoZhongkai/GNOT ***@***.***>
抄送: HaoZhongkai ***@***.***>, Comment ***@***.***>
主题: Re: [HaoZhongkai/GNOT] Viscocity of NS 2D from Li et al (Issue #13)






Hi,
in NS2dC, I wanted to know which viscosity coeff and what train and test split.

Thanks
