### ISSUE TITLE
Explanation of GNOT dataset

### ISSUE THREAD

**Issue by sjh97** [HaoZhongkai/GNOT#14]
Thank you for your good papers. It is helpful for my research.

For my research, I am running the GNOT code. 

However, Because the description of your own dataset is not sufficient, I'm having diffculty applying it to my research.

Could you explain GNOT dataset in more detail?

For example, in Inductor2D dataset,

Data consists of x,y, $\theta$ and input_funcs.

$\theta$ and input_funcs have (11,) and (1,N,2) respectively.

Can I know what **specific physical meaning each variable has**?

If possible, I want to know the physical explanations of $\theta$ and input_funcs in other dataset such as ns2d, heat2d.

Thank you for your help!

**Comment by HaoZhongkai** [comment]
Hi,
  $\theta$ means some parameters describing the shape of the inductor. The input funcs are the corresponding point cloud of the geometric shape.
