### ISSUE TITLE
3D Heat Sink Case

### ISSUE THREAD

**Issue by cfos3120** [HaoZhongkai/GNOT#3]
Great piece of work here. I am particularly interested in the 3D heatsink case, could you please supply the 3D heatsink training data and case handling functions so I can replicate your results?

**Comment by HaoZhongkai** [comment]
Hi, 
    You can find data in this link: https://1drv.ms/u/s!ApNDtoKtGVC6k6AK3AYprkxiZW0qWA?e=7De5vc

best regards,
