### ISSUE TITLE
Running HeatSink 3D

### ISSUE THREAD

**Issue by robColSE** [HaoZhongkai/GNOT#6]
Hi,

First of all great work!

I would like to run this model on a similar example of yours: the heat3D sink. However I have a few questions:

1. the data that you indicate to ([heat3d](https://onedrive.live.com/?authkey=%21ANwGKa5MYmVtKlg&id=BA5019AD82B64393%21315405&cid=BA5019AD82B64393)) is just an array of shape: (1000, 19517, 5). I assume you use 5 functions, would you be so kind to elaborate on what functions/features you use in this array?
2. The same link ([heat3d](https://onedrive.live.com/?authkey=%21ANwGKa5MYmVtKlg&id=BA5019AD82B64393%21315405&cid=BA5019AD82B64393)) also contains a file "Heatsink_Output_XYZ.npy", but where can i find the ground truth?
3. How do you generate 1000 samples? are they just different simulation scenarios?

Looking forward to your answer!

**Comment by HaoZhongkai** [comment]
Hi, sorry for the late response

1. the components are ( temperature T,  velocity vx, vy,vz, pressure p)
2. The inlet velocity and geometry is different for different simulations
