### ISSUE TITLE
How does GNOT work for time-dependent system?

### ISSUE THREAD

**Issue by JiahaoHuang99** [HaoZhongkai/GNOT#9]
Thanks a lot for your nice work!

I am wondering how this model applied for time-dependent system like NS2D since I dont see any detail in both github and the paper. Do you use autoregressive? Or directly change the input and output channel for time dimension.

I would appreciate your response.

**Comment by HaoZhongkai** [comment]
Hi,
  Here we output all channels in a single forward call. We do not see significant improvement using auto-regressive training with multiple steps on NS2d dataset. 
 But we might need more advanced training tricks like Message Passing NO (https://arxiv.org/abs/2202.03376) if the dataset is more complicated.
